- hosts: computers
  gather_facts: no
  strategy: free
  tasks:
  - name: Remove unwanted software using Chocolatey
    win_chocolatey:
      name: '{{ item }}'
      state: absent
    with_items:
    - adobeair
#    - adobereader-de
#    - adobereader
#    - adobereader-update
    - adobeshockwaveplayer
    - autohotkey
    - autoruns
    - avastbrowsercleanup
    - avastfreeantivirus
    - avgantivirusfree
    - avginternetsecurity
    - avgpctuneup
    - avirafreeantivirus
#    - dropbox
    - flashplayerplugin
    - flashplayeractivex
    - freerdp
    - openoffice
    - procexp
    - quicktime
    - windbg
    tags:
    - chocolatey
    - software

- hosts: computerlokaal
  strategy: free
  tasks:
  - name: Remove software
    win_shell: |
      $app = Get-WmiObject -Class Win32_Product -Filter "Name = '{{ item }}'"
      If ($app) {
        $app.Uninstall()
      }
    with_items:
    - Adobe AIR
    - Acrobat Reader X
    - Lenovo Solution Center
    - SDK Debuggers
    tags:
    - windows

#  - name: Disable Windows Features
#    win_feature:
#      name: '{{ item }}'
#      state: absent
#    with_items:
#    - Hearts
#    - Internet-Explorer-Optional-amd64

- hosts: all
  tasks:
  - win_shell: |
      Get-AppxPackage {{ item }} | Remove-AppxPackage
    with_items:
    - 'Microsoft.WindowsAlarms*'
    - Microsoft.People
    - Microsoft.ConnectivityStore
    - Microsoft.WindowsStore
    - Microsoft.XboxApp
    - E046963F.LenovoCompanion
    - Microsoft.WindowsMaps
    - Microsoft.ZuneVideo
    - Microsoft.3DBuilder
    - Microsoft.Office.Sway
    - Microsoft.WindowsCamera
    - Microsoft.ZuneMusic
    - Microsoft.windowscommunicationsapps
    - Microsoft.CommsPhone
    - Microsoft.Windows.Photos
    - Microsoft.BingFinance
    - Microsoft.BingNews
    - Microsoft.MicrosoftSolitaireCollection
    - Microsoft.BingSports
    - Microsoft.BingWeather
    - '*CandyCrush*'
    tags:
    - appx
    - windows

  - raw: powercfg -change -monitor-timeout-ac 15
  - raw: powercfg -change -standby-timeout-ac 60
#  - raw: >
#      $e = (New-Object -Com Shell.Application).NameSpace('shell:::{4234d49b-0245-4df3-b780-3893943456e1}')
#      $e.Items() | %{$_.Verbs()} | ?{$_.Name.replace('&','') -match 'Unpin from Start'} | %{$_.DoIt()}