- hosts: all
  tasks:
  - shell: echo '{{ ansible_date_time.date }} {{ ansible_date_time.time }};{{ ansible_hostname }};{{ ansible_system_description }};{{ ansible_fqdn }};{{ ansible_os_name }};{{ ansible_distribution_version }};{{ mac }};{{ ansible_ip_addresses[0] }};{{ ansible_processor[1] }};{{ (ansible_memtotal_mb/1024)|round|int }}GB;{{ ansible_product_version }};{{ ansible_product_name }};{{ ansible_product_serial }};{{ ansible_lastboot }}' >>systems.csv
    connection: local
    tags: collect
