- hosts: all
  tasks:
  - shell: echo '{{ ansible_date_time.iso8601 }};{{ ansible_hostname }};{{ ansible_system_description }};{{ room }};{{ location }};{{ ansible_fqdn }};{{ ansible_os_name }};{{ ansible_distribution_version }};{{ mac }};{{ ansible_ip_addresses[0] }};{{ ansible_product_version }};{{ ansible_product_name }};{{ ansible_product_serial }};{{ ansible_lastboot }}' >>systems.csv
    connection: local