# Copyright 2016, Dag Wieers <dag@wieers.com>
#
# This playbook configures system-related settings. It is intended to
# be used on newly installed systems. Or whenever this playbook changes.

# Group Policies: https://msdn.microsoft.com/en-us/library/ms815238.aspx

- hosts: computers
  gather_facts: no
  tasks:
  - name: Test system connection
    wait_for_connection:
      timeout: 20

  - name: Create Crombeen directory
    win_file:
      path: '%LOCALAPPDATA%\Crombeen'
      state: directory
    tags: winrm

  - name: Copy ConfigureRemotingForAnsible.ps1 to system
    win_copy:
      src: ConfigureRemotingForAnsible.ps1
      dest: '%LOCALAPPDATA%\Crombeen\ConfigureRemotingForAnsible.ps1'
    tags: winrm

  - name: Configure WinRM from scheduled task weekly
    win_scheduled_task:
      name: ConfigureRemotingForAnsible
      description: Run ConfigureRemotingForAnsible.ps1
      executable: powershell.exe
      arguments: -ExecutionPolicy Bypass -File "$env:LOCALAPPDATA\Crombeen\ConfigureRemotingForAnsible.ps1" -CertValidityDays 3650 -EnableCredSSP -ForceNewSSLCert
      time: 1pm
      frequency: weekly
      days_of_week: monday
      enabled: yes
      user: SYSTEM
    tags: winrm

  - name: Run ConfigureRemotingForAnsible.ps1
    win_shell:
      Powershell.exe -ExecutionPolicy Bypass -File "$env:LOCALAPPDATA\Crombeen\ConfigureRemotingForAnsible.ps1" -CertValidityDays 3650 -EnableCredSSP -ForceNewSSLCert
    register: winrm
    async: 45
    poll: 5
    tags: run-winrm

  - name: Wait for WinRM
    async_status: jid={{ winrm.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 30

  - name: Registry configuration
    win_regedit:
      path: '{{ item.path }}'
      name: '{{ item.name }}'
      data: '{{ item.data|default(None) }}'
      type: '{{ item.type|default("dword") }}'
      state: '{{ item.state|default("present") }}'
    with_items:

    # Network configuration
#    - path: HKLM:\System\ControlSet001\Control\ComputerName\ActiveComputerName
#      name: ComputerName
#      data: '{{ inventory_hostname_short|lower }}'
#      type: string
#    - path: HKLM:\System\ControlSet001\Control\ComputerName\ComputerName
#      name: ComputerName
#      data: '{{ inventory_hostname_short|lower }}'
#      type: string
#    - path: HKLM:\System\ControlSet001\Services\Tcpip\Parameters
#      name: HostName
#      data: '{{ inventory_hostname_short|lower }}'
#      type: string
#    - path: HKLM:\System\ControlSet001\Services\Tcpip\Parameters
#      name: NV HostName
#      data: '{{ inventory_hostname_short|lower }}'
#      type: string
#    - path: HKLM:\System\ControlSet001\Services\Tcpip\Parameters
#      name: Domain
#      data: crombeen.internal
#      type: string
#    - path: HKLM:\System\ControlSet001\Services\Tcpip\Parameters
#      name: NV Domain
#      data: crombeen.internal
#      type: string
    - path: HKLM:\System\ControlSet001\Services\LanmanServer\Parameters
      name: SrvComment
      data: '{{ owner }} ({{ room }})'
      type: string

    # Disable all apps from Windows Store
    - path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: DisableStoreApps
      data: 1

    # Set primary keyboard layout to nl-BE
    - path: HKU:\.DEFAULT\Keyboard Layout\Preload
      name: '1'
      data: 00000813
      type: string
    # Remove secondary keyboard layout
    - path: HKU:\.DEFAULT\Keyboard Layout\Preload
      name: '2'
      state: absent
    # Remove tertiary keyboard layouts
    - path: HKU:\.DEFAULT\Keyboard Layout\Preload
      name: '3'
      state: absent

    # Disable language hotkey
    #   1 = Key Sequence enabled; use LEFT ALT+SHIFT to switch between locales.
    #   2 = Key Sequence enabled; use CTRL+SHIFT to switch between locales.
    #   3 = Key Sequences disabled.
    - path: HKU:\.DEFAULT\Keyboard Layout\Toggle
      name: Language Hotkey
      data: 3
    - path: HKU:\.DEFAULT\Keyboard Layout\Toggle
      name: Layout Hotkey
      data: 3
    - path: HKU:\.DEFAULT\Keyboard Layout\Toggle
      name: Hotkey
      data: 3
#    - path: HKCU:\Keyboard Layout\Toggle
#      name: Language Hotkey
#      data: 3
#    - path: HKCU:\Keyboard Layout\Toggle
#      name: Layout Hotkey
#      data: 3
#    - path: HKCU:\Keyboard Layout\Toggle
#      name: Hotkey
#      data: 3

    - path: HKCU:\Control Panel\Desktop
      name: PreferredUILanguages
      data: 'nl-BE'
      type: multistring
#    -path: HKCU:\Control Panel\Desktop
#     name: PreferredUILanguagesPending
#     data: 'nl-BE'
#     type: multistring

    # Windows 10 Registry Hacks: https://ss64.com/nt/syntax-reghacks.html

    # System Tray - Show all icons (The default for this can be set under HKLM)
    - path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer
      name: EnableAutoTray
      data: 0

    # Do not add "-Shortcut" text to the name of newly created shortcuts.
    - path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer
      name: link
      data: hex:00,00,00,00
      type: binary

    # Show all folders in Explorer including Recycle Bin, Desktop, Control Panel
    - path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: NavPaneShowAllFolders
      data: 0

    # Show hidden files and folders
    - path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: Hidden
      data: 1

    # Hide empty drives in My Computer folder
    - path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: HideDrivesWithNoMedia
      data: 0

    # Do not hide file extensions
    - path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: HideFileExt
      data: 0

    # Show hidden Operating System files
    - path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: ShowSuperHidden
      data: 2

    # Do not show notifications/adverts (OneDrive & new features) in Windows Explorer
    - path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: ShowSyncProviderNotifications
      data: 0

    # Do not slow down search by including all public folders
    - path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: Start_SearchFiles
      data: 1

    # Remove Homegroup from Explorer
    - path: HKLM:\SOFTWARE\Classes\{B4FB3F98-C1EA-428d-A78A-D1F5659CBA93}
      name: System.IsPinnedToNameSpaceTree
      data: 0

    # Prevent "Suggested Applications" to return
    - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Cloud Content
      name: DisableWindowsConsumerFeatures
      data: 1

    # Disable Cortana (Windows 10 Anniversary+)
    - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search
      name: AllowCortana
      data: 0

    # Enable lock timeout settings
#    - path: HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\7516b95f-f776-4464-8c53-06167f40cc99\8EC4B3A5-6868-48c2-BE75-4F3044BE88A7
#      name: Attributes
#      data: 2

    tags: registry

  - name: Set default system locale to nl-BE
    win_shell: |
      Set-Culture nl-BE
      Set-WinSystemLocale nl-BE
      Set-WinHomeLocation -GeoId 21
      Set-WinUserLanguageList -LanguageList nl-BE -Force

  - name: Configure hostname, domain and workgroup
    win_domain_membership:
      hostname: '{{ inventory_hostname_short|lower }}'
      dns_domain_name: crombeen.internal
      workgroup_name: CROMBEENGROUP
      domain_admin_user: '{{ ansible_winrm_username }}'
      domain_admin_password: '{{ ansible_winrm_password }}'
      state: workgroup
    tags: workgroup

  - name: Configure DNS servers
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - 192.168.0.253
      - 8.8.4.4
      - 8.8.8.8
      - 195.238.2.21
      - 195.238.2.22
      - 192.168.0.254
    tags: dns

  - name: Configure time zone
    win_timezone:
      timezone: Romance Standard Time
    tags: timezone

  - name: Disable Zune Music and Zune Video appx
    win_shell: |
      Get-AppxPackage -name "Microsoft.ZuneMusic" | Remove-AppxPackage
      Get-AppxPackage -name "Microsoft.ZuneVideo" | Remove-AppxPackage
    register: appx
    changed_when: "'Deployment operation progress: ' in appx.stderr"
    tags: vlc

  - name: Enable VideoLan Client for ISO/MP3
    win_regedit:
      path: '{{ item.path }}'
      name: '{{ item.name }}'
      data: '{{ item.data|default(None) }}'
      type: '{{ item.type|default("string") }}'
    with_items:
    # ISO support
    - path: HKCR:\VLC.iso
      name: '(default)'
      data: VLC media file (.iso)
    - path: HKCR:\VLC.iso\DefaultIcon
      name: '(default)'
      data: '"%ProgramFiles%\VideoLAN\VLC\vlc.exe",0'
      type: expandstring
    - path: HKCR:\VLC.iso\shell
      name: '(default)'
      data: Open
    - path: HKCR:\VLC.iso\shell\Open
      name: '(default)'
      data: Afspelen
    - path: HKCR:\VLC.iso\shell\Open\command
      name: '(default)'
      data: '"%ProgramFiles%\VideoLAN\VLC\vlc.exe" --started-from-file "%1"'
      type: expandstring
    - path: HKCR:\VLC.iso\shell\PlayWithVLC
      name: '(default)'
      data: VLC Media Player - Afspelen
    - path: HKCR:\VLC.iso\shell\PlayWithVLC\command
      name: '(default)'
      data: '"%ProgramFiles%\VideoLAN\VLC\vlc.exe" --started-from-file --no-playlist-enqueue "%1"'
      type: expandstring
    - path: HKCR:\.iso
      name: '(default)'
      data: VLC.iso

    # ISO/MP3/WMA support
    - path: HKCR:\.iso\OpenWithProgids
      name: VLC.iso
      type: none
    - path: HKCR:\.mkv\OpenWithProgids
      name: VLC.mkv
      type: none
    - path: HKCR:\.mp3\OpenWithProgids
      name: VLC.mp3
      type: none
    - path: HKCR:\.mp4\OpenWithProgids
      name: VLC.mp4
      type: none
    - path: HKCR:\.wma\OpenWithProgids
      name: VLC.wma
      type: none
    tags: vlc

#  - name: Disable hibernate option (removes hibernation file hiberfil.sys)
#    win_shell: |
#      powercfg.exe -h off
#    tags: power

- hosts: computerlokaal:gang:technieklokaal:computer53
  gather_facts: no
  tasks:
  - name: Configuration
    win_regedit:
      path: '{{ item.path }}'
      name: '{{ item.name }}'
      data: '{{ item.data|default(None) }}'
      type: '{{ item.type|default("dword") }}'
    with_items:

    # Disable Windows Remote UAC
    - path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
      name: LocalAccountTokenFilterPolicy
      data: 1

    # Disable and remove the Shut Down command (Leerling)
#    - path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
#      name: NoClose
#      data: 1

    # Disable changing wallpaper
    - path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\ActiveDesktop
      name: NoChangingWallPaper
      data: 1

    # Enable Classic Shell
#    - path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
#      name: ClassicShell
#      data: 1

    # Enable connecting and disconnecting a LAN connection
#    - path: HKCU:\Software\Policies\Microsoft\Windows\Network Connections
#      name: NC_LanConnect
#      data: 0

  - name: Set monitor timeout to 30 minutes
    win_shell: |
      powercfg -change -monitor-timeout-ac 30
    tags: power

  - name: Set sleep timeout to 90 minutes
    win_shell: |
      powercfg -change -standby-timeout-ac 90
    tags: power

#  - name: Set lock timeout to 90 minutes
#    win_shell: |
#      powercfg.exe /SETACVALUEINDEX SCHEME_CURRENT SUB_VIDEO VIDEOCONLOCK 60
#      powercfg.exe /SETACTIVE SCHEME_CURRENT
#    tags: power

  - name: Disable default services
    win_service:
      name: '{{ item }}'
      start_mode: disabled
      state: stopped
    with_items:
    - diagnosticshub.standardcollector.service # Microsoft (R) Diagnostics Hub Standard Collector Service
    - DiagTrack                                # Diagnostics Tracking Service
    - dmwappushservice                         # WAP Push Message Routing Service (see known issues)
    - HomeGroupListener                        # HomeGroup Listener
    - HomeGroupProvider                        # HomeGroup Provider
    - lfsvc                                    # Geolocation Service
    - MapsBroker                               # Downloaded Maps Manager
    - NetTcpPortSharing                        # Net.Tcp Port Sharing Service
    - RemoteAccess                             # Routing and Remote Access
    - RemoteRegistry                           # Remote Registry
    - SharedAccess                             # Internet Connection Sharing (ICS)
    - TrkWks                                   # Distributed Link Tracking Client
    - WbioSrvc                                 # Windows Biometric Service
    #- WlanSvc                                 # WLAN AutoConfig
    - WMPNetworkSvc                            # Windows Media Player Network Sharing Service
    #- wscsvc                                   # Windows Security Center Service
    #- WSearch                                 # Windows Search
    - XblAuthManager                           # Xbox Live Auth Manager
    - XblGameSave                              # Xbox Live Game Save Service
    - XboxNetApiSvc                            # Xbox Live Networking Service
    tags: services

