# Copyright 2016, Dag Wieers <dag@wieers.com>
#
# This playbook configures the desktop (background, icons). It is intended to
# be used on newly installed systems. Or whenever this playbook changes.

# TODO: Group Policies: https://msdn.microsoft.com/en-us/library/ms815238.aspx

- hosts: computers
  gather_facts: no

  tasks:
  - name: Test system connection
    wait_for_connection:
      timeout: 20

  - name: Add shortcut icons
    win_copy:
      src: files/icons/{{ item }}
      dest: '%Public%\Pictures\{{ item }}'
    with_items:
    - bingel.ico
    - computermeester.ico
    - symbaloo.ico
    tags: icons

  - name: Add default desktop shortcuts
    win_shortcut:
      description: '{{ item.desc }}'
      src: '{{ ansible_env["ProgramFiles(x86)"] if "ProgramFiles(x86)" in ansible_env else ansible_env.ProgramFiles }}\Google\Chrome\Application\chrome.exe'
      args: '--new-window {{ item.url }}'
      dest: '{{ item.dest }}'
      icon: '{{ item.icon | default(",0") }}'
      windowstyle: '{{ item.windowstyle | default("normal") }}'
      state: present
    with_items:
    - desc: ComputerMeester website
      url: http://computermeester.be/
      dest: '%Public%\Desktop\Computer Meester.lnk'
      icon: '%Public%\Pictures\computermeester.ico,0'
      windowstyle: maximized
    - desc: Bingel website
      url: https://www.bingel.be/bingel/login/
      dest: '%Public%\Desktop\Bingel.lnk'
      icon: '%Public%\Pictures\bingel.ico,0'
      windowstyle: maximized
    - desc: Symbaloo website
      url: https://www.symbaloo.com/
      dest: '%Public%\Desktop\Symbaloo.lnk'
      icon: '%Public%\Pictures\symbaloo.ico,0'
      windowstyle: maximized
    tags: shortcuts

  - name: Add shortcuts for all computers
    win_shortcut:
      desc: '{{ item.desc }}'
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      icon: '{{ item.icon|default(item.src ~ ",0") }}'
    with_items:
    - desc: Gedeelde ictadmin bestanden
      src: \\diskstation01\ictadmin
      dest: Desktop\ictadmin.lnk
      icon: '%SystemRoot%\System32\imageres.dll,117'
    - desc: Mijn Documenten
      src: '%UserProfile%\Documents'
      dest: '%Public%\Desktop\Documenten.lnk'
      icon: ',0'
    - desc: Prullenbak
      src: shell:RecycleBinFolder
      dest: '%Public%\Desktop\Prullenbak.lnk'
      icon: ',0'
    - desc: Process Explorer
      src: C:\ProgramData\chocolatey\bin\procexp.exe
      dest: Desktop\Process Explorer.lnk
    - desc: Autoruns
      src: C:\ProgramData\chocolatey\bin\autoruns.exe
      dest: Desktop\Autoruns.lnk
    - desc: WakeMeOnLan
      src: \\diskstation01\ictadmin\Tools\WakeMeOnLan\WakeMeOnLan.exe
      dest: Desktop\WakeMeOnLan.lnk
    tags: shortcuts

#  - name: Disable Windows tiles for new users
#    win_copy:
#      src: LayoutModification.xml
#      dest: C:\Users\ictadmin\AppData\Local\Microsoft\Windows\Shell\LayoutModification.xml
#    tags: tiles

  # We prefer to make the Administrator background bright red
  - name: Set red background for user ictadmin
    win_regedit:
      path: '{{ item.path }}'
      name: '{{ item.name }}'
      data: '{{ item.data }}'
      type: '{{ item.type }}'
    with_items:
    - path: HKCU:\Control Panel\Desktop
      name: Wallpaper
      data: ''
      type: string
    - path: HKCU:\Control Panel\Desktop
      name: WallpaperStyle
      data: 10
      type: string
    - path: HKCU:\Control Panel\Colors
      name: Background
      data: '232 17 35'
      type: string
    tags:
    - bg
    - ictadmin
    - registry

  - name: Remove unwanted desktop shortcuts
    win_shortcut:
      dest: '{{ item }}'
      state: absent
    with_items:
    - C:\Users\leerling\Desktop\WinDirStat.lnk
    - '%Public%\Desktop\Audacity.lnk'
    - '%Public%\Desktop\CDex.lnk'
    - '%Public%\Desktop\Google Chrome.lnk'
    - '%Public%\Desktop\Google Earth.lnk'
    - '%Public%\Desktop\Inkscape.lnk'
    - '%Public%\Desktop\Inkscape 0.92.1.lnk'
#    - '%Public%\Desktop\InfraRecorder.lnk'
#    - '%Public%\Desktop\KeePass 2.lnk'
    - '%Public%\Desktop\LibreOffice 5.1.lnk'
    - '%Public%\Desktop\LibreOffice 5.2.lnk'
    - '%Public%\Desktop\LibreOffice 5.3.lnk'
    - '%Public%\Desktop\Mozilla Firefox.lnk'
    - '%Public%\Desktop\VLC media player.lnk'
    tags:
    - cleanup
    - shortcuts

- hosts: computerlokaal:technieklokaal
  tasks:
  - name: Move files on Desktop to Documents
#    win_shell: Move-Item %userprofile%\Desktop\*.* %userprofile%\Documents\ -Force
#    become_user: leerling
    win_shell: Move-Item C:\Users\leerling\Desktop\* C:\Users\leerling\Documents\ -Force
    failed_when: no
    tags:
    - cleanup
    - docs

  - name: Add Music/Video shortcuts
    win_shortcut:
      desc: '{{ item.desc }}'
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      icon: '%SystemRoot%\System32\imageres.dll,{{ item.idx }}'
    with_items:
    - desc: Gedeelde muziek bestanden
      dest: Desktop\Muziek.lnk
      src: \\diskstation01\music
      idx: 103
    - desc: Gedeelde video bestanden
      dest: Desktop\Video.lnk
      src: \\diskstation01\video
      idx: 178
    tags:
    - shares
    - shortcuts

- hosts: klaslokaal:gang:beheer
  tasks:
  - name: Add Music/Video shortcuts
    win_shortcut:
      desc: '{{ item.desc }}'
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      icon: '%SystemRoot%\System32\imageres.dll,{{ item.idx }}'
    with_items:
    - desc: Gedeelde muziek bestanden
      dest: '%Public%\Desktop\Muziek.lnk'
      src: \\diskstation01\music
      idx: 103
    - desc: Gedeelde video bestanden
      dest: '%Public%\Desktop\Video.lnk'
      src: \\diskstation01\video
      idx: 178
    tags:
    - shares
    - shortcuts

# Add KeePass shortcut for all users on admin systems
- hosts: beheer
  tasks:
  - name: Add KeePass shortcuts
    win_shortcut:
      desc: KeePass Password Safe 2
      dest: '%Public%\Desktop\KeePass 2.lnk'
      src: C:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe
    tags: keepass

# Add KeePass shortcut for user ictadmin on all other systems
- hosts: computers:!beheer
  tasks:
  - name: Add KeePass shortcuts
    win_shortcut:
      desc: KeePass Password Safe 2
      dest: Desktop\KeePass 2.lnk
      src: C:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe
    tags: keepass
