- hosts: all
  tasks:
  - name: Create local "Users" group
    win_group:
      name: Users
      description: Local Users
      state: present

  - name: Create local "ictadmin" user
    win_user:
      fullname: ICT Administrator
      name: ictadmin
      description: Used for Ansible automated tasks by the IWT Werkgroep
#      password: '{{ ictadmin_password }}'
      groups: [ Administrators ]
      state: present

#- hosts: all:!computerlokaal
- hosts: computer33
  tasks:
  - name: Create local "leerkracht" user
    win_user:
      fullname: Leerkracht
      name: leerkracht
      description: Persoonlijke gebruiker van de leerkracht van basisschool Crombeen
      account_disabled: no
      groups: [ Users, Gebruikers ]
      password_expired: no
      state: present

  - name: Remove local "leerling" user
    win_user:
      name: leerling
      state: absent

- hosts: computerlokaal:gang
  tasks:
#  - win_user:
#      name: '{{ item }}'
#      state: absent
#    with_items:
#    - '{{ inventory_hostname }}'
#    - computer {{ inventory_hostname[-2:] }}
#    - school{{ inventory_hostname[-1:] }}

  - name: Disable local "Administrator" user
    win_user:
      name: Administrator
      account_disabled: yes
      state: present

  - name: Create local "leerling" user
    win_user:
      fullname: Leerling
      name: leerling
#      password: ''
      description: Gedeelde gebruiker door de leerlingen van basisschool Crombeen
      account_disabled: no
      account_locked: no
      groups: [ Users ]
      user_cannot_change_password: yes
      password_expired: no
      password_never_expires: no
      state: present