# Copyright 2017, Dag Wieers <dag@wieers.com>
#
# This playbook wakes up all/selected desktop systems. It is intended to be
# used before running any Ansible maintenance playbooks system-wide.

- hosts: computers
  gather_facts: no
  serial: 10

  vars:
    wake_server: localhost

  tasks:

  - name: Send magic Wake-On-Lan packet to turn on individual systems via gateway {{ wake_server }}
    win_wakeonlan:
      mac: '{{ mac }}'
      broadcast: 192.168.0.255
    delegate_to: '{{ wake_server }}'
    when: wake_server is defined

  # Advanced idempotent implementation
  - wakeonlan-adv:
      mac: '{{ mac }}'
      broadcast: 192.168.234.1
      port: 9
      check_arp: no
      timeout: 10
    become: yes
    delegate_to: localhost
    when: wake_server == 'localhost'

- hosts: computers
  gather_facts: no
  tasks:
  - name: Wait for the system's WinRM service to come online
    wait_for_connection:
      timeout: 20
